name: Test & Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3.8.4

      - name: Cache Clojure dependencies
        uses: actions/cache@v4
        with:
          key: clj-${{ github.repository }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: clj-${{ github.repository }}-
          path: |
            ~/.gitlibs
            ~/.m2/repository

      - name: Build devShell
        run: nix build .#devShells.x86_64-linux.default

      - name: Run tests and build jar
        run: nix develop -c clojure -T:build ci :snapshot true
